PRODUCT_PACKAGES += \
    AccuratistFont \
    AclonicaFont \
    AmaranteFont \
    BariolFont \
    CagliostroFont \
    CoconFont \
    ComfortaaFont \
    ComicSansFont \
    CoolstoryFont \
    ExotwoFont \
    Fifa2018Font \
    GoogleSansFont \
    GrandHotelFont \
    LGSmartGothicFont \
    LatoFont \
    NokiaPureFont \
    NunitoFont \
    OneplusSlateFont \
    QuandoFont \
    RedressedFont \
    ReemKufiFont \
    RosemaryFont \
    RubikFont \
    SamsungOneFont \
    SonySketchFont \
    StoropiaFont \
    SurferFont \
    UbuntuFont
