PRODUCT_PACKAGES += \
    fonts_customization.xml \
    Accuratist \
    Aclonica \
    Amarante \
    Bariol \
    Cagliostro \
    Cocon \
    Comfortaa \
    ComicSans \
    Coolstory \
    Exotwo \
    Fifa2018 \
    GoogleSans \
    GrandHotel \
    LGSmartGothic \
    Lato \
    NokiaPure \
    Nunito \
    OneplusSlate \
    Quando \
    Redressed \
    ReemKufi \
    Rosemary \
    Rubik \
    SamsungOne \
    SonySketch \
    Storopia \
    Surfer \
    Ubuntu